[colors.primary]
background = "#0a0a07"
foreground = "#c1c1c1"

[colors.cursor]
text = "#0a0a07"
cursor = "#c1c1c1"

[colors.vi_mode_cursor]
text = "#0a0a07"
cursor = "#c1c1c1"

[colors.search.matches]
foreground = "#0a0a07"
background = "#c1c1c1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#676754"
background = "#c1c1c1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a0a07"
red = "#2d7b87"
green = "#388bab"
yellow = "#935f31"
blue = "#c4974f"
magenta = "#c99a5d"
cyan = "#d1ac74"
white = "#c1c1c1"

[colors.bright]
black = "#676754"
red = "#2d7b87"
green = "#388bab"
yellow = "#935f31"
blue = "#c4974f"
magenta = "#c99a5d"
cyan = "#d1ac74"
white = "#c1c1c1"

[colors.dim]
black = "#c1c1c1"
red = "#2d7b87"
green = "#c99a5d"
yellow = "#935f31"
blue = "#c4974f"
magenta = "#388bab"
cyan = "#d1ac74"
white = "#676754"

