--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/chon/Pictures/Wallpapers/Fuji_Temple.jpg"

-- Special
background="#0a0a07"
foreground="#c1c1c1"
cursor="#c1c1c1"

-- Colors
color0="#0a0a07"
color1="#2d7b87"
color2="#388bab"
color3="#935f31"
color4="#c4974f"
color5="#c99a5d"
color6="#d1ac74"
color7="#c1c1c1"
color8="#676754"
color9="#2d7b87"
color10="#388bab"
color11="#935f31"
color12="#c4974f"
color13="#c99a5d"
color14="#d1ac74"
color15="#c1c1c1"
