# Shell variables
# Generated by 'wal'
wallpaper="/home/chon/Pictures/Wallpapers/Fuji_Temple.jpg"

# Special
background='#0a0a07'
foreground='#c1c1c1'
cursor='#c1c1c1'

# Colors
color0='#0a0a07'
color1='#2d7b87'
color2='#388bab'
color3='#935f31'
color4='#c4974f'
color5='#c99a5d'
color6='#d1ac74'
color7='#c1c1c1'
color8='#676754'
color9='#2d7b87'
color10='#388bab'
color11='#935f31'
color12='#c4974f'
color13='#c99a5d'
color14='#d1ac74'
color15='#c1c1c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
